on: [push]
name: newtmptask1



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: deep123
      ResourceGroupLocation: "eastus"
    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
         
      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            pwd
            az aks get-credentials --resource-group deep123 --name muffin25
        
      - uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.15.0' # default is latest stable
        id: install
        
      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            kubectl create namespace ratingapp
            
